// Mocks generated by Mockito 5.4.4 from annotations
// in culicidaelab/test/unit/repositories/classification_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:convert' as _i9;
import 'dart:io' as _i5;
import 'dart:typed_data' as _i10;

import 'package:culicidaelab/models/disease_model.dart' as _i4;
import 'package:culicidaelab/models/mosquito_model.dart' as _i3;
import 'package:culicidaelab/repositories/mosquito_repository.dart' as _i7;
import 'package:culicidaelab/services/classification_service.dart' as _i6;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMosquitoSpecies_2 extends _i1.SmartFake
    implements _i3.MosquitoSpecies {
  _FakeMosquitoSpecies_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDisease_3 extends _i1.SmartFake implements _i4.Disease {
  _FakeDisease_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ClassificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassificationService extends _i1.Mock
    implements _i6.ClassificationService {
  MockClassificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> loadModel() => (super.noSuchMethod(
        Invocation.method(
          #loadModel,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> classifyImage(_i5.File? imageFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #classifyImage,
          [imageFile],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);
}

/// A class which mocks [MosquitoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMosquitoRepository extends _i1.Mock
    implements _i7.MosquitoRepository {
  MockMosquitoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i3.MosquitoSpecies>> getAllMosquitoSpecies(
          String? languageCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllMosquitoSpecies,
          [languageCode],
        ),
        returnValue: _i8.Future<List<_i3.MosquitoSpecies>>.value(
            <_i3.MosquitoSpecies>[]),
      ) as _i8.Future<List<_i3.MosquitoSpecies>>);

  @override
  _i8.Future<_i3.MosquitoSpecies?> getMosquitoSpeciesById(
    String? id,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMosquitoSpeciesById,
          [
            id,
            languageCode,
          ],
        ),
        returnValue: _i8.Future<_i3.MosquitoSpecies?>.value(),
      ) as _i8.Future<_i3.MosquitoSpecies?>);

  @override
  _i8.Future<_i3.MosquitoSpecies?> getMosquitoSpeciesByName(
    String? scientificName,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMosquitoSpeciesByName,
          [
            scientificName,
            languageCode,
          ],
        ),
        returnValue: _i8.Future<_i3.MosquitoSpecies?>.value(),
      ) as _i8.Future<_i3.MosquitoSpecies?>);

  @override
  _i8.Future<List<_i4.Disease>> getAllDiseases(String? languageCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDiseases,
          [languageCode],
        ),
        returnValue: _i8.Future<List<_i4.Disease>>.value(<_i4.Disease>[]),
      ) as _i8.Future<List<_i4.Disease>>);

  @override
  _i8.Future<_i4.Disease?> getDiseaseById(
    String? id,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDiseaseById,
          [
            id,
            languageCode,
          ],
        ),
        returnValue: _i8.Future<_i4.Disease?>.value(),
      ) as _i8.Future<_i4.Disease?>);

  @override
  _i8.Future<List<_i4.Disease>> getDiseasesByVector(
    String? speciesName,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDiseasesByVector,
          [
            speciesName,
            languageCode,
          ],
        ),
        returnValue: _i8.Future<List<_i4.Disease>>.value(<_i4.Disease>[]),
      ) as _i8.Future<List<_i4.Disease>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i8.Future<_i2.Response>);

  @override
  _i8.Future<_i2.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i8.Future<_i2.Response>);

  @override
  _i8.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i9.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response>);

  @override
  _i8.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i9.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response>);

  @override
  _i8.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i9.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response>);

  @override
  _i8.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i9.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response>);

  @override
  _i8.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<String>.value(''),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i10.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i10.Uint8List>.value(_i10.Uint8List(0)),
      ) as _i8.Future<_i10.Uint8List>);

  @override
  _i8.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i8.Future<_i2.StreamedResponse>.value(_FakeStreamedResponse_1(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i8.Future<_i2.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
