// Mocks generated by Mockito 5.4.6 from annotations
// in culicidaelab/test/unit/services/classification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:culicidaelab/services/pytorch_lite_model.dart' as _i2;
import 'package:culicidaelab/services/pytorch_wrapper.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClassificationModel_0 extends _i1.SmartFake
    implements _i2.ClassificationModel {
  _FakeClassificationModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PytorchWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockPytorchWrapper extends _i1.Mock implements _i3.PytorchWrapper {
  MockPytorchWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ClassificationModel> loadClassificationModel(
    String? pathImageModel,
    int? imageWidth,
    int? imageHeight, {
    String? labelPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadClassificationModel,
              [pathImageModel, imageWidth, imageHeight],
              {#labelPath: labelPath},
            ),
            returnValue: _i4.Future<_i2.ClassificationModel>.value(
              _FakeClassificationModel_0(
                this,
                Invocation.method(
                  #loadClassificationModel,
                  [pathImageModel, imageWidth, imageHeight],
                  {#labelPath: labelPath},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ClassificationModel>);
}

/// A class which mocks [ClassificationModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassificationModel extends _i1.Mock
    implements _i2.ClassificationModel {
  MockClassificationModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get labels =>
      (super.noSuchMethod(Invocation.getter(#labels), returnValue: <String>[])
          as List<String>);

  @override
  _i4.Future<String> getImagePrediction(
    _i5.Uint8List? imageAsBytes, {
    List<double>? mean = const [0.485, 0.456, 0.406],
    List<double>? std = const [0.229, 0.224, 0.225],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getImagePrediction,
              [imageAsBytes],
              {#mean: mean, #std: std},
            ),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #getImagePrediction,
                  [imageAsBytes],
                  {#mean: mean, #std: std},
                ),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> getImagePredictionResult(
    _i5.Uint8List? imageAsBytes, {
    List<double>? mean = const [0.485, 0.456, 0.406],
    List<double>? std = const [0.229, 0.224, 0.225],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getImagePredictionResult,
              [imageAsBytes],
              {#mean: mean, #std: std},
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, List<double?>>> getImagePredictionListAndProbs(
    _i5.Uint8List? imageAsBytes, {
    List<double>? mean = const [0.485, 0.456, 0.406],
    List<double>? std = const [0.229, 0.224, 0.225],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getImagePredictionListAndProbs,
              [imageAsBytes],
              {#mean: mean, #std: std},
            ),
            returnValue: _i4.Future<Map<String, List<double?>>>.value(
              <String, List<double?>>{},
            ),
          )
          as _i4.Future<Map<String, List<double?>>>);

  @override
  _i4.Future<List<double?>?> getImagePredictionList(
    _i5.Uint8List? imageAsBytes, {
    List<double>? mean = const [0.485, 0.456, 0.406],
    List<double>? std = const [0.229, 0.224, 0.225],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getImagePredictionList,
              [imageAsBytes],
              {#mean: mean, #std: std},
            ),
            returnValue: _i4.Future<List<double?>?>.value(),
          )
          as _i4.Future<List<double?>?>);

  @override
  _i4.Future<List<double?>?> getImagePredictionListProbabilities(
    _i5.Uint8List? imageAsBytes, {
    List<double>? mean = const [0.485, 0.456, 0.406],
    List<double>? std = const [0.229, 0.224, 0.225],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getImagePredictionListProbabilities,
              [imageAsBytes],
              {#mean: mean, #std: std},
            ),
            returnValue: _i4.Future<List<double?>?>.value(),
          )
          as _i4.Future<List<double?>?>);

  @override
  _i4.Future<String> getImagePredictionFromBytesList(
    List<_i5.Uint8List>? imageAsBytesList,
    int? imageWidth,
    int? imageHeight, {
    List<double>? mean = const [0.485, 0.456, 0.406],
    List<double>? std = const [0.229, 0.224, 0.225],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getImagePredictionFromBytesList,
              [imageAsBytesList, imageWidth, imageHeight],
              {#mean: mean, #std: std},
            ),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #getImagePredictionFromBytesList,
                  [imageAsBytesList, imageWidth, imageHeight],
                  {#mean: mean, #std: std},
                ),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<List<double?>?> getImagePredictionListFromBytesList(
    List<_i5.Uint8List>? imageAsBytesList,
    int? imageWidth,
    int? imageHeight, {
    List<double>? mean = const [0.485, 0.456, 0.406],
    List<double>? std = const [0.229, 0.224, 0.225],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getImagePredictionListFromBytesList,
              [imageAsBytesList, imageWidth, imageHeight],
              {#mean: mean, #std: std},
            ),
            returnValue: _i4.Future<List<double?>?>.value(),
          )
          as _i4.Future<List<double?>?>);

  @override
  _i4.Future<List<double?>?> getImagePredictionListProbabilitiesFromBytesList(
    List<_i5.Uint8List>? imageAsBytesList,
    int? imageWidth,
    int? imageHeight, {
    List<double>? mean = const [0.485, 0.456, 0.406],
    List<double>? std = const [0.229, 0.224, 0.225],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getImagePredictionListProbabilitiesFromBytesList,
              [imageAsBytesList, imageWidth, imageHeight],
              {#mean: mean, #std: std},
            ),
            returnValue: _i4.Future<List<double?>?>.value(),
          )
          as _i4.Future<List<double?>?>);
}
