// Mocks generated by Mockito 5.4.4 from annotations
// in culicidaelab/test/unit/services/user_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i2;
import 'package:uuid/uuid.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i2.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);
  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);
  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);
  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);
  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);
  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);
  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);
  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);
  @override
  _i3.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [Uuid].
///
/// See the documentation for Mockito's code generation for more information.
class MockUuid extends _i1.Mock implements _i4.Uuid {
  MockUuid() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String v1({Map<String, dynamic>? options}) => (super.noSuchMethod(
        Invocation.method(
          #v1,
          [],
          {#options: options},
        ),
        returnValue: '',
      ) as String);
  @override
  void v1buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    int? offset = 0,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #v1buffer,
          [buffer],
          {
            #options: options,
            #offset: offset,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  String v4({Map<String, dynamic>? options}) => (super.noSuchMethod(
        Invocation.method(
          #v4,
          [],
          {#options: options},
        ),
        returnValue: '',
      ) as String);
  @override
  void v4buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    int? offset = 0,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #v4buffer,
          [buffer],
          {
            #options: options,
            #offset: offset,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  String v5(
    String? namespace,
    String? name, {
    Map<String, dynamic>? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v5,
          [
            namespace,
            name,
          ],
          {#options: options},
        ),
        returnValue: '',
      ) as String);
  @override
  void v5buffer(
    String? namespace,
    String? name,
    List<int>? buffer, {
    Map<String, dynamic>? options,
    int? offset = 0,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #v5buffer,
          [
            namespace,
            name,
            buffer,
          ],
          {
            #options: options,
            #offset: offset,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  String v6({Map<String, dynamic>? options}) => (super.noSuchMethod(
        Invocation.method(
          #v6,
          [],
          {#options: options},
        ),
        returnValue: '',
      ) as String);
  @override
  void v6buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    int? offset = 0,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #v6buffer,
          [buffer],
          {
            #options: options,
            #offset: offset,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  String v7({Map<String, dynamic>? options}) => (super.noSuchMethod(
        Invocation.method(
          #v7,
          [],
          {#options: options},
        ),
        returnValue: '',
      ) as String);
  @override
  void v7buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    int? offset = 0,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #v7buffer,
          [buffer],
          {
            #options: options,
            #offset: offset,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  String v8({Map<String, dynamic>? options}) => (super.noSuchMethod(
        Invocation.method(
          #v8,
          [],
          {#options: options},
        ),
        returnValue: '',
      ) as String);
  @override
  void v8buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    int? offset = 0,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #v8buffer,
          [buffer],
          {
            #options: options,
            #offset: offset,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Uint8List parse(
    String? uuid, {
    List<int>? buffer,
    int? offset,
    bool? validate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #parse,
          [uuid],
          {
            #buffer: buffer,
            #offset: offset,
            #validate: validate,
          },
        ),
        returnValue: _i5.Uint8List(0),
      ) as _i5.Uint8List);
  @override
  String unparse(
    List<int>? buffer, {
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #unparse,
          [buffer],
          {#offset: offset},
        ),
        returnValue: '',
      ) as String);
  @override
  bool validate(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #validate,
          [uuid],
        ),
        returnValue: false,
      ) as bool);
}
