// Mocks generated by Mockito 5.4.6 from annotations
// in culicidaelab/test/unit/view_models/mosquito_gallery_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:culicidaelab/models/disease_model.dart' as _i5;
import 'package:culicidaelab/models/mosquito_model.dart' as _i4;
import 'package:culicidaelab/repositories/mosquito_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MosquitoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMosquitoRepository extends _i1.Mock
    implements _i2.MosquitoRepository {
  MockMosquitoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MosquitoSpecies>> getAllMosquitoSpecies(
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllMosquitoSpecies, [languageCode]),
            returnValue: _i3.Future<List<_i4.MosquitoSpecies>>.value(
              <_i4.MosquitoSpecies>[],
            ),
          )
          as _i3.Future<List<_i4.MosquitoSpecies>>);

  @override
  _i3.Future<_i4.MosquitoSpecies?> getMosquitoSpeciesById(
    String? id,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMosquitoSpeciesById, [id, languageCode]),
            returnValue: _i3.Future<_i4.MosquitoSpecies?>.value(),
          )
          as _i3.Future<_i4.MosquitoSpecies?>);

  @override
  _i3.Future<List<_i5.Disease>> getAllDiseases(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#getAllDiseases, [languageCode]),
            returnValue: _i3.Future<List<_i5.Disease>>.value(<_i5.Disease>[]),
          )
          as _i3.Future<List<_i5.Disease>>);

  @override
  _i3.Future<_i5.Disease?> getDiseaseById(String? id, String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#getDiseaseById, [id, languageCode]),
            returnValue: _i3.Future<_i5.Disease?>.value(),
          )
          as _i3.Future<_i5.Disease?>);

  @override
  _i3.Future<List<_i5.Disease>> getDiseasesByVector(
    String? speciesName,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDiseasesByVector, [
              speciesName,
              languageCode,
            ]),
            returnValue: _i3.Future<List<_i5.Disease>>.value(<_i5.Disease>[]),
          )
          as _i3.Future<List<_i5.Disease>>);

  @override
  _i3.Future<_i4.MosquitoSpecies?> getMosquitoSpeciesByName(
    String? scientificName,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMosquitoSpeciesByName, [
              scientificName,
              languageCode,
            ]),
            returnValue: _i3.Future<_i4.MosquitoSpecies?>.value(),
          )
          as _i3.Future<_i4.MosquitoSpecies?>);
}
