// Mocks generated by Mockito 5.4.6 from annotations
// in culicidaelab/test/widget/classification_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i8;
import 'dart:io' as _i2;
import 'dart:typed_data' as _i9;
import 'dart:ui' as _i14;

import 'package:culicidaelab/l10n/app_localizations.dart' as _i11;
import 'package:culicidaelab/models/disease_model.dart' as _i15;
import 'package:culicidaelab/models/mosquito_model.dart' as _i3;
import 'package:culicidaelab/models/observation_model.dart' as _i12;
import 'package:culicidaelab/models/web_prediction_result.dart' as _i13;
import 'package:culicidaelab/repositories/mosquito_repository.dart' as _i16;
import 'package:culicidaelab/view_models/classification_view_model.dart'
    as _i10;
import 'package:image_picker/image_picker.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:shared_preferences/src/shared_preferences_legacy.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_1 extends _i1.SmartFake implements _i2.File {
  _FakeFile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_2 extends _i1.SmartFake implements Uri {
  _FakeUri_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDirectory_3 extends _i1.SmartFake implements _i2.Directory {
  _FakeDirectory_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileSystemEntity_4 extends _i1.SmartFake
    implements _i2.FileSystemEntity {
  _FakeFileSystemEntity_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRandomAccessFile_5 extends _i1.SmartFake
    implements _i2.RandomAccessFile {
  _FakeRandomAccessFile_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSink_6 extends _i1.SmartFake implements _i2.IOSink {
  _FakeIOSink_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileStat_7 extends _i1.SmartFake implements _i2.FileStat {
  _FakeFileStat_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMosquitoSpecies_8 extends _i1.SmartFake
    implements _i3.MosquitoSpecies {
  _FakeMosquitoSpecies_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i4.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i5.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [XFile].
///
/// See the documentation for Mockito's code generation for more information.
class MockXFile extends _i1.Mock implements _i6.XFile {
  MockXFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#path)),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  _i5.Future<void> saveTo(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#saveTo, [path]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> length() =>
      (super.noSuchMethod(
            Invocation.method(#length, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<String> readAsString({
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsString, [], {#encoding: encoding}),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i9.Uint8List> readAsBytes() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytes, []),
            returnValue: _i5.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
          )
          as _i5.Future<_i9.Uint8List>);

  @override
  _i5.Stream<_i9.Uint8List> openRead([int? start, int? end]) =>
      (super.noSuchMethod(
            Invocation.method(#openRead, [start, end]),
            returnValue: _i5.Stream<_i9.Uint8List>.empty(),
          )
          as _i5.Stream<_i9.Uint8List>);

  @override
  _i5.Future<DateTime> lastModified() =>
      (super.noSuchMethod(
            Invocation.method(#lastModified, []),
            returnValue: _i5.Future<DateTime>.value(
              _FakeDateTime_0(this, Invocation.method(#lastModified, [])),
            ),
          )
          as _i5.Future<DateTime>);
}

/// A class which mocks [File].
///
/// See the documentation for Mockito's code generation for more information.
class MockFile extends _i1.Mock implements _i2.File {
  MockFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.File get absolute =>
      (super.noSuchMethod(
            Invocation.getter(#absolute),
            returnValue: _FakeFile_1(this, Invocation.getter(#absolute)),
          )
          as _i2.File);

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#path)),
          )
          as String);

  @override
  Uri get uri =>
      (super.noSuchMethod(
            Invocation.getter(#uri),
            returnValue: _FakeUri_2(this, Invocation.getter(#uri)),
          )
          as Uri);

  @override
  bool get isAbsolute =>
      (super.noSuchMethod(Invocation.getter(#isAbsolute), returnValue: false)
          as bool);

  @override
  _i2.Directory get parent =>
      (super.noSuchMethod(
            Invocation.getter(#parent),
            returnValue: _FakeDirectory_3(this, Invocation.getter(#parent)),
          )
          as _i2.Directory);

  @override
  _i5.Future<_i2.File> create({
    bool? recursive = false,
    bool? exclusive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #recursive: recursive,
              #exclusive: exclusive,
            }),
            returnValue: _i5.Future<_i2.File>.value(
              _FakeFile_1(
                this,
                Invocation.method(#create, [], {
                  #recursive: recursive,
                  #exclusive: exclusive,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.File>);

  @override
  void createSync({bool? recursive = false, bool? exclusive = false}) =>
      super.noSuchMethod(
        Invocation.method(#createSync, [], {
          #recursive: recursive,
          #exclusive: exclusive,
        }),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i2.File> rename(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#rename, [newPath]),
            returnValue: _i5.Future<_i2.File>.value(
              _FakeFile_1(this, Invocation.method(#rename, [newPath])),
            ),
          )
          as _i5.Future<_i2.File>);

  @override
  _i2.File renameSync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#renameSync, [newPath]),
            returnValue: _FakeFile_1(
              this,
              Invocation.method(#renameSync, [newPath]),
            ),
          )
          as _i2.File);

  @override
  _i5.Future<_i2.FileSystemEntity> delete({bool? recursive = false}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#recursive: recursive}),
            returnValue: _i5.Future<_i2.FileSystemEntity>.value(
              _FakeFileSystemEntity_4(
                this,
                Invocation.method(#delete, [], {#recursive: recursive}),
              ),
            ),
          )
          as _i5.Future<_i2.FileSystemEntity>);

  @override
  void deleteSync({bool? recursive = false}) => super.noSuchMethod(
    Invocation.method(#deleteSync, [], {#recursive: recursive}),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.File> copy(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#copy, [newPath]),
            returnValue: _i5.Future<_i2.File>.value(
              _FakeFile_1(this, Invocation.method(#copy, [newPath])),
            ),
          )
          as _i5.Future<_i2.File>);

  @override
  _i2.File copySync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#copySync, [newPath]),
            returnValue: _FakeFile_1(
              this,
              Invocation.method(#copySync, [newPath]),
            ),
          )
          as _i2.File);

  @override
  _i5.Future<int> length() =>
      (super.noSuchMethod(
            Invocation.method(#length, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  int lengthSync() =>
      (super.noSuchMethod(Invocation.method(#lengthSync, []), returnValue: 0)
          as int);

  @override
  _i5.Future<DateTime> lastAccessed() =>
      (super.noSuchMethod(
            Invocation.method(#lastAccessed, []),
            returnValue: _i5.Future<DateTime>.value(
              _FakeDateTime_0(this, Invocation.method(#lastAccessed, [])),
            ),
          )
          as _i5.Future<DateTime>);

  @override
  DateTime lastAccessedSync() =>
      (super.noSuchMethod(
            Invocation.method(#lastAccessedSync, []),
            returnValue: _FakeDateTime_0(
              this,
              Invocation.method(#lastAccessedSync, []),
            ),
          )
          as DateTime);

  @override
  _i5.Future<dynamic> setLastAccessed(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastAccessed, [time]),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  void setLastAccessedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastAccessedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<DateTime> lastModified() =>
      (super.noSuchMethod(
            Invocation.method(#lastModified, []),
            returnValue: _i5.Future<DateTime>.value(
              _FakeDateTime_0(this, Invocation.method(#lastModified, [])),
            ),
          )
          as _i5.Future<DateTime>);

  @override
  DateTime lastModifiedSync() =>
      (super.noSuchMethod(
            Invocation.method(#lastModifiedSync, []),
            returnValue: _FakeDateTime_0(
              this,
              Invocation.method(#lastModifiedSync, []),
            ),
          )
          as DateTime);

  @override
  _i5.Future<dynamic> setLastModified(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastModified, [time]),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  void setLastModifiedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastModifiedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.RandomAccessFile> open({
    _i2.FileMode? mode = _i2.FileMode.read,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#open, [], {#mode: mode}),
            returnValue: _i5.Future<_i2.RandomAccessFile>.value(
              _FakeRandomAccessFile_5(
                this,
                Invocation.method(#open, [], {#mode: mode}),
              ),
            ),
          )
          as _i5.Future<_i2.RandomAccessFile>);

  @override
  _i2.RandomAccessFile openSync({_i2.FileMode? mode = _i2.FileMode.read}) =>
      (super.noSuchMethod(
            Invocation.method(#openSync, [], {#mode: mode}),
            returnValue: _FakeRandomAccessFile_5(
              this,
              Invocation.method(#openSync, [], {#mode: mode}),
            ),
          )
          as _i2.RandomAccessFile);

  @override
  _i5.Stream<List<int>> openRead([int? start, int? end]) =>
      (super.noSuchMethod(
            Invocation.method(#openRead, [start, end]),
            returnValue: _i5.Stream<List<int>>.empty(),
          )
          as _i5.Stream<List<int>>);

  @override
  _i2.IOSink openWrite({
    _i2.FileMode? mode = _i2.FileMode.write,
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#openWrite, [], {
              #mode: mode,
              #encoding: encoding,
            }),
            returnValue: _FakeIOSink_6(
              this,
              Invocation.method(#openWrite, [], {
                #mode: mode,
                #encoding: encoding,
              }),
            ),
          )
          as _i2.IOSink);

  @override
  _i5.Future<_i9.Uint8List> readAsBytes() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytes, []),
            returnValue: _i5.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
          )
          as _i5.Future<_i9.Uint8List>);

  @override
  _i9.Uint8List readAsBytesSync() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytesSync, []),
            returnValue: _i9.Uint8List(0),
          )
          as _i9.Uint8List);

  @override
  _i5.Future<String> readAsString({
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsString, [], {#encoding: encoding}),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  String readAsStringSync({_i8.Encoding? encoding = const _i8.Utf8Codec()}) =>
      (super.noSuchMethod(
            Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            ),
          )
          as String);

  @override
  _i5.Future<List<String>> readAsLines({
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsLines, [], {#encoding: encoding}),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  List<String> readAsLinesSync({
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsLinesSync, [], {#encoding: encoding}),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i5.Future<_i2.File> writeAsBytes(
    List<int>? bytes, {
    _i2.FileMode? mode = _i2.FileMode.write,
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsBytes,
              [bytes],
              {#mode: mode, #flush: flush},
            ),
            returnValue: _i5.Future<_i2.File>.value(
              _FakeFile_1(
                this,
                Invocation.method(
                  #writeAsBytes,
                  [bytes],
                  {#mode: mode, #flush: flush},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.File>);

  @override
  void writeAsBytesSync(
    List<int>? bytes, {
    _i2.FileMode? mode = _i2.FileMode.write,
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(#writeAsBytesSync, [bytes], {#mode: mode, #flush: flush}),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.File> writeAsString(
    String? contents, {
    _i2.FileMode? mode = _i2.FileMode.write,
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsString,
              [contents],
              {#mode: mode, #encoding: encoding, #flush: flush},
            ),
            returnValue: _i5.Future<_i2.File>.value(
              _FakeFile_1(
                this,
                Invocation.method(
                  #writeAsString,
                  [contents],
                  {#mode: mode, #encoding: encoding, #flush: flush},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.File>);

  @override
  void writeAsStringSync(
    String? contents, {
    _i2.FileMode? mode = _i2.FileMode.write,
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #writeAsStringSync,
      [contents],
      {#mode: mode, #encoding: encoding, #flush: flush},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> exists() =>
      (super.noSuchMethod(
            Invocation.method(#exists, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  bool existsSync() =>
      (super.noSuchMethod(
            Invocation.method(#existsSync, []),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<String> resolveSymbolicLinks() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinks, []),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#resolveSymbolicLinks, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  String resolveSymbolicLinksSync() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinksSync, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#resolveSymbolicLinksSync, []),
            ),
          )
          as String);

  @override
  _i5.Future<_i2.FileStat> stat() =>
      (super.noSuchMethod(
            Invocation.method(#stat, []),
            returnValue: _i5.Future<_i2.FileStat>.value(
              _FakeFileStat_7(this, Invocation.method(#stat, [])),
            ),
          )
          as _i5.Future<_i2.FileStat>);

  @override
  _i2.FileStat statSync() =>
      (super.noSuchMethod(
            Invocation.method(#statSync, []),
            returnValue: _FakeFileStat_7(
              this,
              Invocation.method(#statSync, []),
            ),
          )
          as _i2.FileStat);

  @override
  _i5.Stream<_i2.FileSystemEvent> watch({
    int? events = 15,
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [], {
              #events: events,
              #recursive: recursive,
            }),
            returnValue: _i5.Stream<_i2.FileSystemEvent>.empty(),
          )
          as _i5.Stream<_i2.FileSystemEvent>);
}

/// A class which mocks [ClassificationViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassificationViewModel extends _i1.Mock
    implements _i10.ClassificationViewModel {
  MockClassificationViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get modelId =>
      (super.noSuchMethod(
            Invocation.getter(#modelId),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#modelId),
            ),
          )
          as String);

  @override
  _i10.ClassificationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i10.ClassificationState.initial,
          )
          as _i10.ClassificationState);

  @override
  bool get hasImage =>
      (super.noSuchMethod(Invocation.getter(#hasImage), returnValue: false)
          as bool);

  @override
  bool get isProcessing =>
      (super.noSuchMethod(Invocation.getter(#isProcessing), returnValue: false)
          as bool);

  @override
  bool get isSubmitting =>
      (super.noSuchMethod(Invocation.getter(#isSubmitting), returnValue: false)
          as bool);

  @override
  bool get isFetchingWebPrediction =>
      (super.noSuchMethod(
            Invocation.getter(#isFetchingWebPrediction),
            returnValue: false,
          )
          as bool);

  @override
  bool get shouldShowDiseaseRiskButton =>
      (super.noSuchMethod(
            Invocation.getter(#shouldShowDiseaseRiskButton),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> initModel(_i11.AppLocalizations? localizations) =>
      (super.noSuchMethod(
            Invocation.method(#initModel, [localizations]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> pickImage(
    _i6.ImageSource? source,
    _i11.AppLocalizations? localizations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#pickImage, [source, localizations]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> classifyImage(_i11.AppLocalizations? localizations) =>
      (super.noSuchMethod(
            Invocation.method(#classifyImage, [localizations]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchWebPrediction(_i11.AppLocalizations? localizations) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWebPrediction, [localizations]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i12.Observation?> submitObservation({
    required _i3.ClassificationResult? localResult,
    required _i13.WebPredictionResult? webPrediction,
    required double? latitude,
    required double? longitude,
    required String? notes,
    required _i11.AppLocalizations? localizations,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitObservation, [], {
              #localResult: localResult,
              #webPrediction: webPrediction,
              #latitude: latitude,
              #longitude: longitude,
              #notes: notes,
              #localizations: localizations,
            }),
            returnValue: _i5.Future<_i12.Observation?>.value(),
          )
          as _i5.Future<_i12.Observation?>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void setState(_i10.ClassificationState? state) => super.noSuchMethod(
    Invocation.method(#setState, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void setImageFile(_i2.File? file) => super.noSuchMethod(
    Invocation.method(#setImageFile, [file]),
    returnValueForMissingStub: null,
  );

  @override
  void setResult(_i3.ClassificationResult? result) => super.noSuchMethod(
    Invocation.method(#setResult, [result]),
    returnValueForMissingStub: null,
  );

  @override
  void setErrorMessage(String? message) => super.noSuchMethod(
    Invocation.method(#setErrorMessage, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AppLocalizations].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalizations extends _i1.Mock implements _i11.AppLocalizations {
  MockAppLocalizations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get localeName =>
      (super.noSuchMethod(
            Invocation.getter(#localeName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#localeName),
            ),
          )
          as String);

  @override
  String get appTitle =>
      (super.noSuchMethod(
            Invocation.getter(#appTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#appTitle),
            ),
          )
          as String);

  @override
  String get homePageTitle =>
      (super.noSuchMethod(
            Invocation.getter(#homePageTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#homePageTitle),
            ),
          )
          as String);

  @override
  String get homePageBannerTitle =>
      (super.noSuchMethod(
            Invocation.getter(#homePageBannerTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#homePageBannerTitle),
            ),
          )
          as String);

  @override
  String get homePageBannerSubtitle =>
      (super.noSuchMethod(
            Invocation.getter(#homePageBannerSubtitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#homePageBannerSubtitle),
            ),
          )
          as String);

  @override
  String get classifyMosquitoButtonTitle =>
      (super.noSuchMethod(
            Invocation.getter(#classifyMosquitoButtonTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#classifyMosquitoButtonTitle),
            ),
          )
          as String);

  @override
  String get classifyMosquitoButtonSubtitle =>
      (super.noSuchMethod(
            Invocation.getter(#classifyMosquitoButtonSubtitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#classifyMosquitoButtonSubtitle),
            ),
          )
          as String);

  @override
  String get mosquitoGalleryButtonTitle =>
      (super.noSuchMethod(
            Invocation.getter(#mosquitoGalleryButtonTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#mosquitoGalleryButtonTitle),
            ),
          )
          as String);

  @override
  String get mosquitoGalleryButtonSubtitle =>
      (super.noSuchMethod(
            Invocation.getter(#mosquitoGalleryButtonSubtitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#mosquitoGalleryButtonSubtitle),
            ),
          )
          as String);

  @override
  String get diseasesInfoButtonTitle =>
      (super.noSuchMethod(
            Invocation.getter(#diseasesInfoButtonTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#diseasesInfoButtonTitle),
            ),
          )
          as String);

  @override
  String get diseasesInfoButtonSubtitle =>
      (super.noSuchMethod(
            Invocation.getter(#diseasesInfoButtonSubtitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#diseasesInfoButtonSubtitle),
            ),
          )
          as String);

  @override
  String get appDisclaimerTitle =>
      (super.noSuchMethod(
            Invocation.getter(#appDisclaimerTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#appDisclaimerTitle),
            ),
          )
          as String);

  @override
  String get appDisclaimerBody =>
      (super.noSuchMethod(
            Invocation.getter(#appDisclaimerBody),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#appDisclaimerBody),
            ),
          )
          as String);

  @override
  String get appFooterGrantInfo =>
      (super.noSuchMethod(
            Invocation.getter(#appFooterGrantInfo),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#appFooterGrantInfo),
            ),
          )
          as String);

  @override
  String get loadingModelDialogTitle =>
      (super.noSuchMethod(
            Invocation.getter(#loadingModelDialogTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#loadingModelDialogTitle),
            ),
          )
          as String);

  @override
  String get loadingModelDialogContent =>
      (super.noSuchMethod(
            Invocation.getter(#loadingModelDialogContent),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#loadingModelDialogContent),
            ),
          )
          as String);

  @override
  String get classificationScreenTitle =>
      (super.noSuchMethod(
            Invocation.getter(#classificationScreenTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#classificationScreenTitle),
            ),
          )
          as String);

  @override
  String get uploadImageHint =>
      (super.noSuchMethod(
            Invocation.getter(#uploadImageHint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#uploadImageHint),
            ),
          )
          as String);

  @override
  String get uploadImageSubHint =>
      (super.noSuchMethod(
            Invocation.getter(#uploadImageSubHint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#uploadImageSubHint),
            ),
          )
          as String);

  @override
  String get speciesInfoButton =>
      (super.noSuchMethod(
            Invocation.getter(#speciesInfoButton),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#speciesInfoButton),
            ),
          )
          as String);

  @override
  String get diseaseRisksButton =>
      (super.noSuchMethod(
            Invocation.getter(#diseaseRisksButton),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#diseaseRisksButton),
            ),
          )
          as String);

  @override
  String get noKnownDiseaseRisks =>
      (super.noSuchMethod(
            Invocation.getter(#noKnownDiseaseRisks),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noKnownDiseaseRisks),
            ),
          )
          as String);

  @override
  String get potentialDiseaseRisksTitle =>
      (super.noSuchMethod(
            Invocation.getter(#potentialDiseaseRisksTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#potentialDiseaseRisksTitle),
            ),
          )
          as String);

  @override
  String get potentialDiseaseRisksSubtitle =>
      (super.noSuchMethod(
            Invocation.getter(#potentialDiseaseRisksSubtitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#potentialDiseaseRisksSubtitle),
            ),
          )
          as String);

  @override
  String get disclaimerEducationalUse =>
      (super.noSuchMethod(
            Invocation.getter(#disclaimerEducationalUse),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#disclaimerEducationalUse),
            ),
          )
          as String);

  @override
  String get cameraButtonLabel =>
      (super.noSuchMethod(
            Invocation.getter(#cameraButtonLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#cameraButtonLabel),
            ),
          )
          as String);

  @override
  String get galleryButtonLabel =>
      (super.noSuchMethod(
            Invocation.getter(#galleryButtonLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#galleryButtonLabel),
            ),
          )
          as String);

  @override
  String get resetButtonLabel =>
      (super.noSuchMethod(
            Invocation.getter(#resetButtonLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#resetButtonLabel),
            ),
          )
          as String);

  @override
  String get analyzingImage =>
      (super.noSuchMethod(
            Invocation.getter(#analyzingImage),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#analyzingImage),
            ),
          )
          as String);

  @override
  String get analyzeButton =>
      (super.noSuchMethod(
            Invocation.getter(#analyzeButton),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#analyzeButton),
            ),
          )
          as String);

  @override
  String get noImageSelectedTitle =>
      (super.noSuchMethod(
            Invocation.getter(#noImageSelectedTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noImageSelectedTitle),
            ),
          )
          as String);

  @override
  String get noImageSelectedSubtitle =>
      (super.noSuchMethod(
            Invocation.getter(#noImageSelectedSubtitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noImageSelectedSubtitle),
            ),
          )
          as String);

  @override
  String get unknownSpecies =>
      (super.noSuchMethod(
            Invocation.getter(#unknownSpecies),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#unknownSpecies),
            ),
          )
          as String);

  @override
  String get errorNoImageSelected =>
      (super.noSuchMethod(
            Invocation.getter(#errorNoImageSelected),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#errorNoImageSelected),
            ),
          )
          as String);

  @override
  String get mosquitoGalleryScreenTitle =>
      (super.noSuchMethod(
            Invocation.getter(#mosquitoGalleryScreenTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#mosquitoGalleryScreenTitle),
            ),
          )
          as String);

  @override
  String get searchMosquitoSpeciesHint =>
      (super.noSuchMethod(
            Invocation.getter(#searchMosquitoSpeciesHint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#searchMosquitoSpeciesHint),
            ),
          )
          as String);

  @override
  String get anErrorOccurred =>
      (super.noSuchMethod(
            Invocation.getter(#anErrorOccurred),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#anErrorOccurred),
            ),
          )
          as String);

  @override
  String get retryButton =>
      (super.noSuchMethod(
            Invocation.getter(#retryButton),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#retryButton),
            ),
          )
          as String);

  @override
  String get noMosquitoSpeciesFound =>
      (super.noSuchMethod(
            Invocation.getter(#noMosquitoSpeciesFound),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noMosquitoSpeciesFound),
            ),
          )
          as String);

  @override
  String get tryDifferentSearchTerm =>
      (super.noSuchMethod(
            Invocation.getter(#tryDifferentSearchTerm),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#tryDifferentSearchTerm),
            ),
          )
          as String);

  @override
  String get noKnownDiseaseVectors =>
      (super.noSuchMethod(
            Invocation.getter(#noKnownDiseaseVectors),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noKnownDiseaseVectors),
            ),
          )
          as String);

  @override
  String get diseaseDetailScreenDescription =>
      (super.noSuchMethod(
            Invocation.getter(#diseaseDetailScreenDescription),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#diseaseDetailScreenDescription),
            ),
          )
          as String);

  @override
  String get diseaseDetailScreenSymptoms =>
      (super.noSuchMethod(
            Invocation.getter(#diseaseDetailScreenSymptoms),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#diseaseDetailScreenSymptoms),
            ),
          )
          as String);

  @override
  String get diseaseDetailScreenTreatment =>
      (super.noSuchMethod(
            Invocation.getter(#diseaseDetailScreenTreatment),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#diseaseDetailScreenTreatment),
            ),
          )
          as String);

  @override
  String get diseaseDetailScreenPrevention =>
      (super.noSuchMethod(
            Invocation.getter(#diseaseDetailScreenPrevention),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#diseaseDetailScreenPrevention),
            ),
          )
          as String);

  @override
  String get diseaseDetailScreenPrevalence =>
      (super.noSuchMethod(
            Invocation.getter(#diseaseDetailScreenPrevalence),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#diseaseDetailScreenPrevalence),
            ),
          )
          as String);

  @override
  String get diseaseDetailScreenTransmittedBy =>
      (super.noSuchMethod(
            Invocation.getter(#diseaseDetailScreenTransmittedBy),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#diseaseDetailScreenTransmittedBy),
            ),
          )
          as String);

  @override
  String get diseaseDetailScreenUnknownVector =>
      (super.noSuchMethod(
            Invocation.getter(#diseaseDetailScreenUnknownVector),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#diseaseDetailScreenUnknownVector),
            ),
          )
          as String);

  @override
  String get diseaseDetailScreenInfoNotAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#diseaseDetailScreenInfoNotAvailable),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#diseaseDetailScreenInfoNotAvailable),
            ),
          )
          as String);

  @override
  String get diseaseDetailScreenVectorsNotAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#diseaseDetailScreenVectorsNotAvailable),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#diseaseDetailScreenVectorsNotAvailable),
            ),
          )
          as String);

  @override
  String get mosquitoDetailScreenDescription =>
      (super.noSuchMethod(
            Invocation.getter(#mosquitoDetailScreenDescription),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#mosquitoDetailScreenDescription),
            ),
          )
          as String);

  @override
  String get mosquitoDetailScreenHabitat =>
      (super.noSuchMethod(
            Invocation.getter(#mosquitoDetailScreenHabitat),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#mosquitoDetailScreenHabitat),
            ),
          )
          as String);

  @override
  String get mosquitoDetailScreenDistribution =>
      (super.noSuchMethod(
            Invocation.getter(#mosquitoDetailScreenDistribution),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#mosquitoDetailScreenDistribution),
            ),
          )
          as String);

  @override
  String get mosquitoDetailScreenAssociatedDiseases =>
      (super.noSuchMethod(
            Invocation.getter(#mosquitoDetailScreenAssociatedDiseases),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#mosquitoDetailScreenAssociatedDiseases),
            ),
          )
          as String);

  @override
  String get mosquitoDetailScreenNoAssociatedDiseases =>
      (super.noSuchMethod(
            Invocation.getter(#mosquitoDetailScreenNoAssociatedDiseases),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#mosquitoDetailScreenNoAssociatedDiseases),
            ),
          )
          as String);

  @override
  String get diseaseInfoScreenTitle =>
      (super.noSuchMethod(
            Invocation.getter(#diseaseInfoScreenTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#diseaseInfoScreenTitle),
            ),
          )
          as String);

  @override
  String get searchDiseasesHint =>
      (super.noSuchMethod(
            Invocation.getter(#searchDiseasesHint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#searchDiseasesHint),
            ),
          )
          as String);

  @override
  String get noDiseasesFound =>
      (super.noSuchMethod(
            Invocation.getter(#noDiseasesFound),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noDiseasesFound),
            ),
          )
          as String);

  @override
  String get classificationServiceUnknownSpeciesCommonName =>
      (super.noSuchMethod(
            Invocation.getter(#classificationServiceUnknownSpeciesCommonName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#classificationServiceUnknownSpeciesCommonName),
            ),
          )
          as String);

  @override
  String get classificationServiceUnknownSpeciesDescription =>
      (super.noSuchMethod(
            Invocation.getter(#classificationServiceUnknownSpeciesDescription),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(
                #classificationServiceUnknownSpeciesDescription,
              ),
            ),
          )
          as String);

  @override
  String get classificationServiceUnknownSpeciesHabitat =>
      (super.noSuchMethod(
            Invocation.getter(#classificationServiceUnknownSpeciesHabitat),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#classificationServiceUnknownSpeciesHabitat),
            ),
          )
          as String);

  @override
  String get classificationServiceUnknownSpeciesDistribution =>
      (super.noSuchMethod(
            Invocation.getter(#classificationServiceUnknownSpeciesDistribution),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(
                #classificationServiceUnknownSpeciesDistribution,
              ),
            ),
          )
          as String);

  @override
  String get classificationServiceErrorModelNotLoaded =>
      (super.noSuchMethod(
            Invocation.getter(#classificationServiceErrorModelNotLoaded),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#classificationServiceErrorModelNotLoaded),
            ),
          )
          as String);

  @override
  String get classificationServiceErrorModelLoadingFailed =>
      (super.noSuchMethod(
            Invocation.getter(#classificationServiceErrorModelLoadingFailed),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#classificationServiceErrorModelLoadingFailed),
            ),
          )
          as String);

  @override
  String get homePageMosquitoActivityMapButtonTitle =>
      (super.noSuchMethod(
            Invocation.getter(#homePageMosquitoActivityMapButtonTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#homePageMosquitoActivityMapButtonTitle),
            ),
          )
          as String);

  @override
  String get homePageMosquitoActivityMapButtonSubtitle =>
      (super.noSuchMethod(
            Invocation.getter(#homePageMosquitoActivityMapButtonSubtitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#homePageMosquitoActivityMapButtonSubtitle),
            ),
          )
          as String);

  @override
  String get webViewScreenTitleMosquitoMap =>
      (super.noSuchMethod(
            Invocation.getter(#webViewScreenTitleMosquitoMap),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#webViewScreenTitleMosquitoMap),
            ),
          )
          as String);

  @override
  String get webViewFailedToLoad =>
      (super.noSuchMethod(
            Invocation.getter(#webViewFailedToLoad),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#webViewFailedToLoad),
            ),
          )
          as String);

  @override
  String get webViewRetryButton =>
      (super.noSuchMethod(
            Invocation.getter(#webViewRetryButton),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#webViewRetryButton),
            ),
          )
          as String);

  @override
  String get tooltipSelectLanguage =>
      (super.noSuchMethod(
            Invocation.getter(#tooltipSelectLanguage),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#tooltipSelectLanguage),
            ),
          )
          as String);

  @override
  String get addDetailsButton =>
      (super.noSuchMethod(
            Invocation.getter(#addDetailsButton),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#addDetailsButton),
            ),
          )
          as String);

  @override
  String get thankYouForParticipation =>
      (super.noSuchMethod(
            Invocation.getter(#thankYouForParticipation),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#thankYouForParticipation),
            ),
          )
          as String);

  @override
  String get observationDetailsTitle =>
      (super.noSuchMethod(
            Invocation.getter(#observationDetailsTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#observationDetailsTitle),
            ),
          )
          as String);

  @override
  String get locationSectionTitle =>
      (super.noSuchMethod(
            Invocation.getter(#locationSectionTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#locationSectionTitle),
            ),
          )
          as String);

  @override
  String get locationInstruction =>
      (super.noSuchMethod(
            Invocation.getter(#locationInstruction),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#locationInstruction),
            ),
          )
          as String);

  @override
  String get fieldRequiredError =>
      (super.noSuchMethod(
            Invocation.getter(#fieldRequiredError),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#fieldRequiredError),
            ),
          )
          as String);

  @override
  String get locationRequiredError =>
      (super.noSuchMethod(
            Invocation.getter(#locationRequiredError),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#locationRequiredError),
            ),
          )
          as String);

  @override
  String get notesLabel =>
      (super.noSuchMethod(
            Invocation.getter(#notesLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#notesLabel),
            ),
          )
          as String);

  @override
  String get notesHint =>
      (super.noSuchMethod(
            Invocation.getter(#notesHint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#notesHint),
            ),
          )
          as String);

  @override
  String get submitObservationButton =>
      (super.noSuchMethod(
            Invocation.getter(#submitObservationButton),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#submitObservationButton),
            ),
          )
          as String);

  @override
  String get predictionSummaryTitle =>
      (super.noSuchMethod(
            Invocation.getter(#predictionSummaryTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#predictionSummaryTitle),
            ),
          )
          as String);

  @override
  String get latitudeLabel =>
      (super.noSuchMethod(
            Invocation.getter(#latitudeLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#latitudeLabel),
            ),
          )
          as String);

  @override
  String get longitudeLabel =>
      (super.noSuchMethod(
            Invocation.getter(#longitudeLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#longitudeLabel),
            ),
          )
          as String);

  @override
  String get submittingObservation =>
      (super.noSuchMethod(
            Invocation.getter(#submittingObservation),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#submittingObservation),
            ),
          )
          as String);

  @override
  String get fetchingWebPrediction =>
      (super.noSuchMethod(
            Invocation.getter(#fetchingWebPrediction),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#fetchingWebPrediction),
            ),
          )
          as String);

  @override
  String get errorFailedWebPrediction =>
      (super.noSuchMethod(
            Invocation.getter(#errorFailedWebPrediction),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#errorFailedWebPrediction),
            ),
          )
          as String);

  @override
  String get speciesNotDefinedWebPrediction =>
      (super.noSuchMethod(
            Invocation.getter(#speciesNotDefinedWebPrediction),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#speciesNotDefinedWebPrediction),
            ),
          )
          as String);

  @override
  String get retryButtonLabel =>
      (super.noSuchMethod(
            Invocation.getter(#retryButtonLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#retryButtonLabel),
            ),
          )
          as String);

  @override
  String speciesLabel(String? speciesName) =>
      (super.noSuchMethod(
            Invocation.method(#speciesLabel, [speciesName]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#speciesLabel, [speciesName]),
            ),
          )
          as String);

  @override
  String commonNameLabel(String? commonName) =>
      (super.noSuchMethod(
            Invocation.method(#commonNameLabel, [commonName]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#commonNameLabel, [commonName]),
            ),
          )
          as String);

  @override
  String confidenceLabel(String? confidenceValue) =>
      (super.noSuchMethod(
            Invocation.method(#confidenceLabel, [confidenceValue]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#confidenceLabel, [confidenceValue]),
            ),
          )
          as String);

  @override
  String inferenceTimeLabel(int? timeValue) =>
      (super.noSuchMethod(
            Invocation.method(#inferenceTimeLabel, [timeValue]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#inferenceTimeLabel, [timeValue]),
            ),
          )
          as String);

  @override
  String errorFailedToPickImage(String? error) =>
      (super.noSuchMethod(
            Invocation.method(#errorFailedToPickImage, [error]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#errorFailedToPickImage, [error]),
            ),
          )
          as String);

  @override
  String errorClassificationFailed(String? error) =>
      (super.noSuchMethod(
            Invocation.method(#errorClassificationFailed, [error]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#errorClassificationFailed, [error]),
            ),
          )
          as String);

  @override
  String errorFailedToLoadModel(String? error) =>
      (super.noSuchMethod(
            Invocation.method(#errorFailedToLoadModel, [error]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#errorFailedToLoadModel, [error]),
            ),
          )
          as String);

  @override
  String habitatLabel(String? habitat) =>
      (super.noSuchMethod(
            Invocation.method(#habitatLabel, [habitat]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#habitatLabel, [habitat]),
            ),
          )
          as String);

  @override
  String diseaseVectorsCount(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#diseaseVectorsCount, [count]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#diseaseVectorsCount, [count]),
            ),
          )
          as String);

  @override
  String vectorsLabel(String? vectors) =>
      (super.noSuchMethod(
            Invocation.method(#vectorsLabel, [vectors]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#vectorsLabel, [vectors]),
            ),
          )
          as String);

  @override
  String prevalenceLabel(String? prevalence) =>
      (super.noSuchMethod(
            Invocation.method(#prevalenceLabel, [prevalence]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#prevalenceLabel, [prevalence]),
            ),
          )
          as String);

  @override
  String viewModelErrorFailedToLoadDiseases(String? error) =>
      (super.noSuchMethod(
            Invocation.method(#viewModelErrorFailedToLoadDiseases, [error]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#viewModelErrorFailedToLoadDiseases, [error]),
            ),
          )
          as String);

  @override
  String viewModelErrorFailedToLoadDisease(String? error) =>
      (super.noSuchMethod(
            Invocation.method(#viewModelErrorFailedToLoadDisease, [error]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#viewModelErrorFailedToLoadDisease, [error]),
            ),
          )
          as String);

  @override
  String viewModelErrorFailedToLoadDiseasesForVector(String? error) =>
      (super.noSuchMethod(
            Invocation.method(#viewModelErrorFailedToLoadDiseasesForVector, [
              error,
            ]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#viewModelErrorFailedToLoadDiseasesForVector, [
                error,
              ]),
            ),
          )
          as String);

  @override
  String viewModelErrorFailedToLoadMosquitoSpecies(String? error) =>
      (super.noSuchMethod(
            Invocation.method(#viewModelErrorFailedToLoadMosquitoSpecies, [
              error,
            ]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#viewModelErrorFailedToLoadMosquitoSpecies, [
                error,
              ]),
            ),
          )
          as String);

  @override
  String submissionIdLabel(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#submissionIdLabel, [id]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#submissionIdLabel, [id]),
            ),
          )
          as String);

  @override
  String errorSubmissionFailed(String? error) =>
      (super.noSuchMethod(
            Invocation.method(#errorSubmissionFailed, [error]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#errorSubmissionFailed, [error]),
            ),
          )
          as String);
}

/// A class which mocks [MosquitoSpecies].
///
/// See the documentation for Mockito's code generation for more information.
class MockMosquitoSpecies extends _i1.Mock implements _i3.MosquitoSpecies {
  MockMosquitoSpecies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  String get commonName =>
      (super.noSuchMethod(
            Invocation.getter(#commonName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#commonName),
            ),
          )
          as String);

  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
          )
          as String);

  @override
  String get habitat =>
      (super.noSuchMethod(
            Invocation.getter(#habitat),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#habitat),
            ),
          )
          as String);

  @override
  String get distribution =>
      (super.noSuchMethod(
            Invocation.getter(#distribution),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#distribution),
            ),
          )
          as String);

  @override
  String get imageUrl =>
      (super.noSuchMethod(
            Invocation.getter(#imageUrl),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#imageUrl),
            ),
          )
          as String);

  @override
  List<String> get diseases =>
      (super.noSuchMethod(Invocation.getter(#diseases), returnValue: <String>[])
          as List<String>);
}

/// A class which mocks [ClassificationResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassificationResult extends _i1.Mock
    implements _i3.ClassificationResult {
  MockClassificationResult() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MosquitoSpecies get species =>
      (super.noSuchMethod(
            Invocation.getter(#species),
            returnValue: _FakeMosquitoSpecies_8(
              this,
              Invocation.getter(#species),
            ),
          )
          as _i3.MosquitoSpecies);

  @override
  double get confidence =>
      (super.noSuchMethod(Invocation.getter(#confidence), returnValue: 0.0)
          as double);

  @override
  int get inferenceTime =>
      (super.noSuchMethod(Invocation.getter(#inferenceTime), returnValue: 0)
          as int);

  @override
  List<_i15.Disease> get relatedDiseases =>
      (super.noSuchMethod(
            Invocation.getter(#relatedDiseases),
            returnValue: <_i15.Disease>[],
          )
          as List<_i15.Disease>);

  @override
  _i2.File get imageFile =>
      (super.noSuchMethod(
            Invocation.getter(#imageFile),
            returnValue: _FakeFile_1(this, Invocation.getter(#imageFile)),
          )
          as _i2.File);
}

/// A class which mocks [Disease].
///
/// See the documentation for Mockito's code generation for more information.
class MockDisease extends _i1.Mock implements _i15.Disease {
  MockDisease() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
          )
          as String);

  @override
  String get symptoms =>
      (super.noSuchMethod(
            Invocation.getter(#symptoms),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#symptoms),
            ),
          )
          as String);

  @override
  String get treatment =>
      (super.noSuchMethod(
            Invocation.getter(#treatment),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#treatment),
            ),
          )
          as String);

  @override
  String get prevention =>
      (super.noSuchMethod(
            Invocation.getter(#prevention),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#prevention),
            ),
          )
          as String);

  @override
  List<String> get vectors =>
      (super.noSuchMethod(Invocation.getter(#vectors), returnValue: <String>[])
          as List<String>);

  @override
  String get prevalence =>
      (super.noSuchMethod(
            Invocation.getter(#prevalence),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#prevalence),
            ),
          )
          as String);

  @override
  String get imageUrl =>
      (super.noSuchMethod(
            Invocation.getter(#imageUrl),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#imageUrl),
            ),
          )
          as String);
}

/// A class which mocks [MosquitoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMosquitoRepository extends _i1.Mock
    implements _i16.MosquitoRepository {
  MockMosquitoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.MosquitoSpecies>> getAllMosquitoSpecies(
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllMosquitoSpecies, [languageCode]),
            returnValue: _i5.Future<List<_i3.MosquitoSpecies>>.value(
              <_i3.MosquitoSpecies>[],
            ),
          )
          as _i5.Future<List<_i3.MosquitoSpecies>>);

  @override
  _i5.Future<_i3.MosquitoSpecies?> getMosquitoSpeciesById(
    String? id,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMosquitoSpeciesById, [id, languageCode]),
            returnValue: _i5.Future<_i3.MosquitoSpecies?>.value(),
          )
          as _i5.Future<_i3.MosquitoSpecies?>);

  @override
  _i5.Future<List<_i15.Disease>> getAllDiseases(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#getAllDiseases, [languageCode]),
            returnValue: _i5.Future<List<_i15.Disease>>.value(<_i15.Disease>[]),
          )
          as _i5.Future<List<_i15.Disease>>);

  @override
  _i5.Future<_i15.Disease?> getDiseaseById(String? id, String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#getDiseaseById, [id, languageCode]),
            returnValue: _i5.Future<_i15.Disease?>.value(),
          )
          as _i5.Future<_i15.Disease?>);

  @override
  _i5.Future<List<_i15.Disease>> getDiseasesByVector(
    String? speciesName,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDiseasesByVector, [
              speciesName,
              languageCode,
            ]),
            returnValue: _i5.Future<List<_i15.Disease>>.value(<_i15.Disease>[]),
          )
          as _i5.Future<List<_i15.Disease>>);

  @override
  _i5.Future<_i3.MosquitoSpecies?> getMosquitoSpeciesByName(
    String? scientificName,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMosquitoSpeciesByName, [
              scientificName,
              languageCode,
            ]),
            returnValue: _i5.Future<_i3.MosquitoSpecies?>.value(),
          )
          as _i5.Future<_i3.MosquitoSpecies?>);
}
