// Mocks generated by Mockito 5.4.6 from annotations
// in culicidaelab/test/unit/classification_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:convert' as _i11;
import 'dart:io' as _i5;
import 'dart:typed_data' as _i12;

import 'package:culicidaelab/models/mosquito_model.dart' as _i2;
import 'package:culicidaelab/models/observation_model.dart' as _i4;
import 'package:culicidaelab/models/web_prediction_result.dart' as _i3;
import 'package:culicidaelab/repositories/classification_repository.dart'
    as _i7;
import 'package:culicidaelab/services/user_service.dart' as _i9;
import 'package:image_picker/image_picker.dart' as _i13;
import 'package:image_picker_platform_interface/image_picker_platform_interface.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClassificationResult_0 extends _i1.SmartFake
    implements _i2.ClassificationResult {
  _FakeClassificationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebPredictionResult_1 extends _i1.SmartFake
    implements _i3.WebPredictionResult {
  _FakeWebPredictionResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeObservation_2 extends _i1.SmartFake implements _i4.Observation {
  _FakeObservation_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_3 extends _i1.SmartFake implements _i5.File {
  _FakeFile_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_4 extends _i1.SmartFake implements Uri {
  _FakeUri_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDirectory_5 extends _i1.SmartFake implements _i5.Directory {
  _FakeDirectory_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileSystemEntity_6 extends _i1.SmartFake
    implements _i5.FileSystemEntity {
  _FakeFileSystemEntity_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_7 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRandomAccessFile_8 extends _i1.SmartFake
    implements _i5.RandomAccessFile {
  _FakeRandomAccessFile_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSink_9 extends _i1.SmartFake implements _i5.IOSink {
  _FakeIOSink_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileStat_10 extends _i1.SmartFake implements _i5.FileStat {
  _FakeFileStat_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLostDataResponse_11 extends _i1.SmartFake
    implements _i6.LostDataResponse {
  _FakeLostDataResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ClassificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassificationRepository extends _i1.Mock
    implements _i7.ClassificationRepository {
  MockClassificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> loadModel() =>
      (super.noSuchMethod(
            Invocation.method(#loadModel, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i2.ClassificationResult> classifyImage(
    _i5.File? imageFile,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#classifyImage, [imageFile, languageCode]),
            returnValue: _i8.Future<_i2.ClassificationResult>.value(
              _FakeClassificationResult_0(
                this,
                Invocation.method(#classifyImage, [imageFile, languageCode]),
              ),
            ),
          )
          as _i8.Future<_i2.ClassificationResult>);

  @override
  _i8.Future<_i3.WebPredictionResult> getWebPrediction(_i5.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#getWebPrediction, [imageFile]),
            returnValue: _i8.Future<_i3.WebPredictionResult>.value(
              _FakeWebPredictionResult_1(
                this,
                Invocation.method(#getWebPrediction, [imageFile]),
              ),
            ),
          )
          as _i8.Future<_i3.WebPredictionResult>);

  @override
  _i8.Future<_i4.Observation> submitObservation({
    required Map<String, dynamic>? finalPayload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitObservation, [], {
              #finalPayload: finalPayload,
            }),
            returnValue: _i8.Future<_i4.Observation>.value(
              _FakeObservation_2(
                this,
                Invocation.method(#submitObservation, [], {
                  #finalPayload: finalPayload,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.Observation>);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i9.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String> getUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getUserId, []),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(this, Invocation.method(#getUserId, [])),
            ),
          )
          as _i8.Future<String>);
}

/// A class which mocks [File].
///
/// See the documentation for Mockito's code generation for more information.
class MockFile extends _i1.Mock implements _i5.File {
  MockFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.File get absolute =>
      (super.noSuchMethod(
            Invocation.getter(#absolute),
            returnValue: _FakeFile_3(this, Invocation.getter(#absolute)),
          )
          as _i5.File);

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  Uri get uri =>
      (super.noSuchMethod(
            Invocation.getter(#uri),
            returnValue: _FakeUri_4(this, Invocation.getter(#uri)),
          )
          as Uri);

  @override
  bool get isAbsolute =>
      (super.noSuchMethod(Invocation.getter(#isAbsolute), returnValue: false)
          as bool);

  @override
  _i5.Directory get parent =>
      (super.noSuchMethod(
            Invocation.getter(#parent),
            returnValue: _FakeDirectory_5(this, Invocation.getter(#parent)),
          )
          as _i5.Directory);

  @override
  _i8.Future<_i5.File> create({
    bool? recursive = false,
    bool? exclusive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #recursive: recursive,
              #exclusive: exclusive,
            }),
            returnValue: _i8.Future<_i5.File>.value(
              _FakeFile_3(
                this,
                Invocation.method(#create, [], {
                  #recursive: recursive,
                  #exclusive: exclusive,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.File>);

  @override
  void createSync({bool? recursive = false, bool? exclusive = false}) =>
      super.noSuchMethod(
        Invocation.method(#createSync, [], {
          #recursive: recursive,
          #exclusive: exclusive,
        }),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i5.File> rename(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#rename, [newPath]),
            returnValue: _i8.Future<_i5.File>.value(
              _FakeFile_3(this, Invocation.method(#rename, [newPath])),
            ),
          )
          as _i8.Future<_i5.File>);

  @override
  _i5.File renameSync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#renameSync, [newPath]),
            returnValue: _FakeFile_3(
              this,
              Invocation.method(#renameSync, [newPath]),
            ),
          )
          as _i5.File);

  @override
  _i8.Future<_i5.FileSystemEntity> delete({bool? recursive = false}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#recursive: recursive}),
            returnValue: _i8.Future<_i5.FileSystemEntity>.value(
              _FakeFileSystemEntity_6(
                this,
                Invocation.method(#delete, [], {#recursive: recursive}),
              ),
            ),
          )
          as _i8.Future<_i5.FileSystemEntity>);

  @override
  void deleteSync({bool? recursive = false}) => super.noSuchMethod(
    Invocation.method(#deleteSync, [], {#recursive: recursive}),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i5.File> copy(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#copy, [newPath]),
            returnValue: _i8.Future<_i5.File>.value(
              _FakeFile_3(this, Invocation.method(#copy, [newPath])),
            ),
          )
          as _i8.Future<_i5.File>);

  @override
  _i5.File copySync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#copySync, [newPath]),
            returnValue: _FakeFile_3(
              this,
              Invocation.method(#copySync, [newPath]),
            ),
          )
          as _i5.File);

  @override
  _i8.Future<int> length() =>
      (super.noSuchMethod(
            Invocation.method(#length, []),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  int lengthSync() =>
      (super.noSuchMethod(Invocation.method(#lengthSync, []), returnValue: 0)
          as int);

  @override
  _i8.Future<DateTime> lastAccessed() =>
      (super.noSuchMethod(
            Invocation.method(#lastAccessed, []),
            returnValue: _i8.Future<DateTime>.value(
              _FakeDateTime_7(this, Invocation.method(#lastAccessed, [])),
            ),
          )
          as _i8.Future<DateTime>);

  @override
  DateTime lastAccessedSync() =>
      (super.noSuchMethod(
            Invocation.method(#lastAccessedSync, []),
            returnValue: _FakeDateTime_7(
              this,
              Invocation.method(#lastAccessedSync, []),
            ),
          )
          as DateTime);

  @override
  _i8.Future<dynamic> setLastAccessed(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastAccessed, [time]),
            returnValue: _i8.Future<dynamic>.value(),
          )
          as _i8.Future<dynamic>);

  @override
  void setLastAccessedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastAccessedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<DateTime> lastModified() =>
      (super.noSuchMethod(
            Invocation.method(#lastModified, []),
            returnValue: _i8.Future<DateTime>.value(
              _FakeDateTime_7(this, Invocation.method(#lastModified, [])),
            ),
          )
          as _i8.Future<DateTime>);

  @override
  DateTime lastModifiedSync() =>
      (super.noSuchMethod(
            Invocation.method(#lastModifiedSync, []),
            returnValue: _FakeDateTime_7(
              this,
              Invocation.method(#lastModifiedSync, []),
            ),
          )
          as DateTime);

  @override
  _i8.Future<dynamic> setLastModified(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastModified, [time]),
            returnValue: _i8.Future<dynamic>.value(),
          )
          as _i8.Future<dynamic>);

  @override
  void setLastModifiedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastModifiedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i5.RandomAccessFile> open({
    _i5.FileMode? mode = _i5.FileMode.read,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#open, [], {#mode: mode}),
            returnValue: _i8.Future<_i5.RandomAccessFile>.value(
              _FakeRandomAccessFile_8(
                this,
                Invocation.method(#open, [], {#mode: mode}),
              ),
            ),
          )
          as _i8.Future<_i5.RandomAccessFile>);

  @override
  _i5.RandomAccessFile openSync({_i5.FileMode? mode = _i5.FileMode.read}) =>
      (super.noSuchMethod(
            Invocation.method(#openSync, [], {#mode: mode}),
            returnValue: _FakeRandomAccessFile_8(
              this,
              Invocation.method(#openSync, [], {#mode: mode}),
            ),
          )
          as _i5.RandomAccessFile);

  @override
  _i8.Stream<List<int>> openRead([int? start, int? end]) =>
      (super.noSuchMethod(
            Invocation.method(#openRead, [start, end]),
            returnValue: _i8.Stream<List<int>>.empty(),
          )
          as _i8.Stream<List<int>>);

  @override
  _i5.IOSink openWrite({
    _i5.FileMode? mode = _i5.FileMode.write,
    _i11.Encoding? encoding = const _i11.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#openWrite, [], {
              #mode: mode,
              #encoding: encoding,
            }),
            returnValue: _FakeIOSink_9(
              this,
              Invocation.method(#openWrite, [], {
                #mode: mode,
                #encoding: encoding,
              }),
            ),
          )
          as _i5.IOSink);

  @override
  _i8.Future<_i12.Uint8List> readAsBytes() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytes, []),
            returnValue: _i8.Future<_i12.Uint8List>.value(_i12.Uint8List(0)),
          )
          as _i8.Future<_i12.Uint8List>);

  @override
  _i12.Uint8List readAsBytesSync() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytesSync, []),
            returnValue: _i12.Uint8List(0),
          )
          as _i12.Uint8List);

  @override
  _i8.Future<String> readAsString({
    _i11.Encoding? encoding = const _i11.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsString, [], {#encoding: encoding}),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  String readAsStringSync({_i11.Encoding? encoding = const _i11.Utf8Codec()}) =>
      (super.noSuchMethod(
            Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            ),
          )
          as String);

  @override
  _i8.Future<List<String>> readAsLines({
    _i11.Encoding? encoding = const _i11.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsLines, [], {#encoding: encoding}),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  List<String> readAsLinesSync({
    _i11.Encoding? encoding = const _i11.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsLinesSync, [], {#encoding: encoding}),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i8.Future<_i5.File> writeAsBytes(
    List<int>? bytes, {
    _i5.FileMode? mode = _i5.FileMode.write,
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsBytes,
              [bytes],
              {#mode: mode, #flush: flush},
            ),
            returnValue: _i8.Future<_i5.File>.value(
              _FakeFile_3(
                this,
                Invocation.method(
                  #writeAsBytes,
                  [bytes],
                  {#mode: mode, #flush: flush},
                ),
              ),
            ),
          )
          as _i8.Future<_i5.File>);

  @override
  void writeAsBytesSync(
    List<int>? bytes, {
    _i5.FileMode? mode = _i5.FileMode.write,
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(#writeAsBytesSync, [bytes], {#mode: mode, #flush: flush}),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i5.File> writeAsString(
    String? contents, {
    _i5.FileMode? mode = _i5.FileMode.write,
    _i11.Encoding? encoding = const _i11.Utf8Codec(),
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsString,
              [contents],
              {#mode: mode, #encoding: encoding, #flush: flush},
            ),
            returnValue: _i8.Future<_i5.File>.value(
              _FakeFile_3(
                this,
                Invocation.method(
                  #writeAsString,
                  [contents],
                  {#mode: mode, #encoding: encoding, #flush: flush},
                ),
              ),
            ),
          )
          as _i8.Future<_i5.File>);

  @override
  void writeAsStringSync(
    String? contents, {
    _i5.FileMode? mode = _i5.FileMode.write,
    _i11.Encoding? encoding = const _i11.Utf8Codec(),
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #writeAsStringSync,
      [contents],
      {#mode: mode, #encoding: encoding, #flush: flush},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> exists() =>
      (super.noSuchMethod(
            Invocation.method(#exists, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  bool existsSync() =>
      (super.noSuchMethod(
            Invocation.method(#existsSync, []),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<String> resolveSymbolicLinks() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinks, []),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#resolveSymbolicLinks, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  String resolveSymbolicLinksSync() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinksSync, []),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#resolveSymbolicLinksSync, []),
            ),
          )
          as String);

  @override
  _i8.Future<_i5.FileStat> stat() =>
      (super.noSuchMethod(
            Invocation.method(#stat, []),
            returnValue: _i8.Future<_i5.FileStat>.value(
              _FakeFileStat_10(this, Invocation.method(#stat, [])),
            ),
          )
          as _i8.Future<_i5.FileStat>);

  @override
  _i5.FileStat statSync() =>
      (super.noSuchMethod(
            Invocation.method(#statSync, []),
            returnValue: _FakeFileStat_10(
              this,
              Invocation.method(#statSync, []),
            ),
          )
          as _i5.FileStat);

  @override
  _i8.Stream<_i5.FileSystemEvent> watch({
    int? events = 15,
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [], {
              #events: events,
              #recursive: recursive,
            }),
            returnValue: _i8.Stream<_i5.FileSystemEvent>.empty(),
          )
          as _i8.Stream<_i5.FileSystemEvent>);
}

/// A class which mocks [ImagePicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePicker extends _i1.Mock implements _i13.ImagePicker {
  MockImagePicker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.XFile?> pickImage({
    required _i6.ImageSource? source,
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    _i6.CameraDevice? preferredCameraDevice = _i6.CameraDevice.rear,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickImage, [], {
              #source: source,
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #preferredCameraDevice: preferredCameraDevice,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i8.Future<_i6.XFile?>.value(),
          )
          as _i8.Future<_i6.XFile?>);

  @override
  _i8.Future<List<_i6.XFile>> pickMultiImage({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultiImage, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #limit: limit,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i8.Future<List<_i6.XFile>>.value(<_i6.XFile>[]),
          )
          as _i8.Future<List<_i6.XFile>>);

  @override
  _i8.Future<_i6.XFile?> pickMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMedia, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i8.Future<_i6.XFile?>.value(),
          )
          as _i8.Future<_i6.XFile?>);

  @override
  _i8.Future<List<_i6.XFile>> pickMultipleMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultipleMedia, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #limit: limit,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i8.Future<List<_i6.XFile>>.value(<_i6.XFile>[]),
          )
          as _i8.Future<List<_i6.XFile>>);

  @override
  _i8.Future<_i6.XFile?> pickVideo({
    required _i6.ImageSource? source,
    _i6.CameraDevice? preferredCameraDevice = _i6.CameraDevice.rear,
    Duration? maxDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickVideo, [], {
              #source: source,
              #preferredCameraDevice: preferredCameraDevice,
              #maxDuration: maxDuration,
            }),
            returnValue: _i8.Future<_i6.XFile?>.value(),
          )
          as _i8.Future<_i6.XFile?>);

  @override
  _i8.Future<_i6.LostDataResponse> retrieveLostData() =>
      (super.noSuchMethod(
            Invocation.method(#retrieveLostData, []),
            returnValue: _i8.Future<_i6.LostDataResponse>.value(
              _FakeLostDataResponse_11(
                this,
                Invocation.method(#retrieveLostData, []),
              ),
            ),
          )
          as _i8.Future<_i6.LostDataResponse>);

  @override
  bool supportsImageSource(_i6.ImageSource? source) =>
      (super.noSuchMethod(
            Invocation.method(#supportsImageSource, [source]),
            returnValue: false,
          )
          as bool);
}
